### ISSUE TITLE
ppmlhdfe aweights

### ISSUE THREAD

**Issue by CorinnaHa** [sergiocorreia/ppmlhdfe#2]
Hi Sergio,

it would be great if you could program the command "aweights" for ppmlhdfe. The commands "fweight" and "pweight" work well. 

Thanks!
Corinna

**Comment by sergiocorreia** [comment]
Hi Corinna,

The reason for not implementing aweights is that ppmlhdfe needs to use pweights to control for the fact that you might be modelling a "pseudo" poisson model (ie a model where the variance might not follow what you expect from a poisson distribution).

We can combine that with frequency weights, but because pweights is just robust aweights, it was not something you can do in pseudo models.

Are you thinking about running a (non pseudo) poisson model, or something else?

**Comment by CorinnaHa** [comment]
Thanks for your fast response and the explanation! I am thinking about running a pseudo poisson model using the number of diagnoses per county as outcome variable.  I intended to weight observations by the number of individuals living in each county using the command aweights.

**Comment by sergiocorreia** [comment]
I don't think aweights is valid in this case, instead of just using pweights

**Comment by CorinnaHa** [comment]
Ok, thanks for your help!
